# Generated by Django 4.1.7 on 2023-03-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AlterModelOptions(
            name="tag", options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.RemoveField(model_name="tag", name="articles",),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                related_name="article", through="articles.Scope", to="articles.tag"
            ),
        ),
    ]
